### ISSUE TITLE
log scale histograms

### ISSUE THREAD

**Issue by tolot27** [wdecoster/nanocomp#12]
It would be nice to have log scale at the x axis for the histograms of read lengths. Currently, only the "Comparing log length" plot is scaled.

**Comment by wdecoster** [comment]
Hi tolot27,

I have just added this feature. Thanks for the suggestion!
An example screenshot is shown below. It is available in NanoComp v0.22.0, which I just pushed to PyPI. Bioconda recipes will be updated later this weekend.

Let me know if you have other suggestions/issues/...

Cheers,
Wouter

![image](https://user-images.githubusercontent.com/11660522/45585501-aaf4ed80-b8e5-11e8-9398-1a7e89805a13.png)
