### ISSUE TITLE
Discrepancies  in stats output between different bam alignments of same fasta file

### ISSUE THREAD

**Issue by ggstatgen** [wdecoster/nanocomp#13]
Hi team

I have some pacbio long read data and I thought I'd give nanocomp a go because it's a great tool and don't see any particular issue that should limit it to nanopore data (please correct me if I'm wrong).

I've run it on 2 alignment files (sorted bams) generated from the same fasta file using two different aligners, ngmlr and minimap2. I found that some of the stats in the outfile file produced by Nanocomp (NanoStats.txt) are different and was wondering if there is an issue or I am misunderstanding the output.

Shouldn't the fields 'total bases' and 'number of reads' be the same across aligners? Based on my experience with short reads, I'd have thought all reads from the fasta/fastq are present in the bam, even ones that failed to align. Hence why I thought the two statistics above should be the same? Thanks!

**Comment by ggstatgen** [comment]
Thanks Wouter - but then I guess I don't understand what is the difference between the two following stats:

1. "Total bases"
2. "Total bases aligned"

For example, for my minimap2 .bam file, I get
Total bases: 6,662,368,077.0
Total bases aligned: 6,065,476,462.0

And for my ngmlr .bam file I get:
Total bases: 7,213,179,976.0
Total bases aligned: 5,662,314,400.0

Thanks,

**Comment by wdecoster** [comment]
That difference is explained by soft clipping of your reads.

If you have just one read (toy example) with CIGAR 100M4S (4 nucleotides soft-clipped) you'll get:

```
Total bases:	104
Total bases aligned:	100
```
Meaning "for all reads which have an alignment there are 104 nucleotides - and for all reads 100 of those nucleotides are aligned"...


I see that you also get the following, which is not intuitive and maybe could be considered a bug:
```
Read length N50:	104
```

So,  this difference is explained by having aligned reads with unaligned bases.

I agree that this is not entirely clear in the stats report and would be beneficial to be more explicit about this, so I'll leave this issue open.

Cheers,
Wouter

**Comment by aspitaleri** [comment]
> Hi,
> 
> It should indeed work perfectly fine for PacBio data as well. Probably also for Illumina open_mouth
> You are right that the unaligned reads are present in the sam/bam file (for both ngmlr and minimap2), but these are discarded by my tools. Therefore also the number of nucleotides is different.
> 
> Cheers,
> Wouter

Hi,
I tried NanoComp on a set of bam files from short illumina sequences generated both by bwa -mem and minimap2 -ax sr but it does not work:

Traceback (most recent call last):
  File "/home/aspitaleri/.local/bin/NanoComp", line 11, in <module>
    sys.exit(main())
  File "/home/aspitaleri/.local/lib/python3.6/site-packages/nanocomp/NanoComp.py", line 34, in main
    combine="track")
  File "/home/aspitaleri/.local/lib/python3.6/site-packages/nanoget/nanoget.py", line 90, in get_input
    dfs=[out for out in executor.map(extraction_function, files)],
  File "/home/aspitaleri/.local/lib/python3.6/site-packages/nanoget/nanoget.py", line 90, in <listcomp>
    dfs=[out for out in executor.map(extraction_function, files)],
  File "/home/aspitaleri/.conda/envs/nanopore/lib/python3.6/concurrent/futures/process.py", line 366, in _chain_from_iterable_of_lists
    for element in iterable:
  File "/home/aspitaleri/.conda/envs/nanopore/lib/python3.6/concurrent/futures/_base.py", line 586, in result_iterator
    yield fs.pop().result()
  File "/home/aspitaleri/.conda/envs/nanopore/lib/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/home/aspitaleri/.conda/envs/nanopore/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
TypeError: reduce() arg 2 must support iteration

I am using NanoComp v 1.9.2
Thanks
