### ISSUE TITLE
Add cram support

### ISSUE THREAD

**Issue by wdecoster** [wdecoster/nanocomp#14]
Add option to get stats with --cram analogous to NanoPlot

**Comment by jvhaarst** [comment]
Could you also add ubam here, as you did for NanoStat ?
It would be even greater if I could hand NanoComp the pickle from NanoPlot, and that it would start from there.

**Comment by wdecoster** [comment]
ubam and cram: I will take care of it, probably next week

Using the pickle is slightly more difficult, it would be nice but it's not a perfect replacement of the data that NanoComp is working on. It's a good suggestion and I'll think about it.

**Comment by wdecoster** [comment]
v1.10.0 supports cram and ubam
