### ISSUE TITLE
NanoStats "Number of reads" greater than input fastq reads

### ISSUE THREAD

**Issue by kkowalden** [wdecoster/nanocomp#17]
Hello,

I am aligning a set of Oxford Nanopore genomic FASTQ reads from 3 different basecallers to a "reference" genome using minimap2 to evaluate basecaller accuracy.

When I run nanocomp on the sorted bam files, in all cases the NanoStats.txt file reports a greater "number of reads" than available in the FASTQ files.  I assume this is due to "supplementary alignments" observed in some long read alignment bam files.  

I see in the log file the number of mapped and unmapped reads, and then primary alignments.  The number of primary alignments listed are all greater than the number of input reads. Is the bam file filtered on a particular set of SAM flags? How does this affect nanocomp calculations?

Thanks,
Kim

**Comment by wdecoster** [comment]
Only primary aligned reads are used for plotting and statistics. There is no other further on SAM flags. Supplementary alignments will indeed increase the number of reads.

**Comment by wdecoster** [comment]
Let me know if you have further questions!
