### ISSUE TITLE
NanoComp raw data

### ISSUE THREAD

**Issue by aspitaleri** [wdecoster/nanocomp#18]
Hi
NanoComp analysis for multi bam files is very useful. I am wondering whether it is possible to get raw data from the analysis in order to perform additional plots. For instance, it would be interesting to plot the distribution of the percent of identity of a set of bam files instead to have only the violin/blox plots.
Thanks

**Comment by wdecoster** [comment]
If you would check the command line help with `NanoComp --help` you would see there is a `--raw` option, which will give you a tab separated file of the raw data, and a `--store` option which will give you a Python Pickle file containing the pandas DataFrame used for plotting.

I'm not sure what you mean with "plot the distribution of the percent identity", as the violin plots already give you a distribution of the identity. But please let me know if there is anything else that I could add to NanoComp and I will consider it.

**Comment by aspitaleri** [comment]
Hi
yes indeed that I was looking for but for reason I didn't see .... quite embarrassing. Basically, when you compare a dataset of bam files, you get indeed a plot percent identity vs samples as violin plot. Since for a huge dataset sample the plot is a bit a mess, I was thinking to make a total distribution of the distribution of the whole dataset.

**Comment by aspitaleri** [comment]
I have done and so far I get this plot:
![nanocomp-freq](https://user-images.githubusercontent.com/41744541/60271931-7fcb1000-98f3-11e9-8412-6234cd9c16b6.png)
in gnuplot:
n=100 #number of intervals
max=100. #max value
min=0. #min value
width=(max-min)/n #interval width
#function used to map a value to the intervals
hist(x,width)=width*floor(x/width)+width/2.0
set xrange [min:max]
set yrange [0:]
p "NanoComp-data.tsv" u (hist($7,width)):(1.0) smooth freq w boxes lc rgb"green" notitle

**Comment by wdecoster** [comment]
So you want to combine the reads from all bam files to generate that plot? In that case, it seems a better fit for NanoPlot to add a histogram as you showed above. I'll add it later this week if this solves your request.

**Comment by aspitaleri** [comment]
ok thanks

**Comment by wdecoster** [comment]
NanoPlot version 1.26.0 (which I just made available through pip) will generate a histogram of percent identities. The plot will be in .html format.

**Comment by LeilyR** [comment]
Hi, I am having a very naive question, is percent identity is in this case an equivalent for the mapping rate?

**Comment by wdecoster** [comment]
I don't see how this issue is connected to your question? It would be more appropriate to open a separate issue...

Anyway, no, it's not. The mapping rate would the fraction/percentage of the reads which could get aligned somewhere in the genome, while the percent identity of a read is the percentages of nucleotides that match with the reference sequence. As such it's a measurement of the accuracy of the reads.

**Comment by LeilyR** [comment]
Hi @wdecoster , You are right, I might have been mistaken. Thanks a lot for the detailed explantation.
