### ISSUE TITLE
Comulativeyieldplot_gigabases raw data

### ISSUE THREAD

**Issue by anja999** [wdecoster/nanocomp#19]
Dear all,
is there any way of exporting data (in txt or tsv file) from Comulativeyieldplot_gigabases plot?

Many thanks,

Anja

**Comment by wdecoster** [comment]
Hi Anja,

Right now there is no way to do that, which data exactly do you have in mind?

Cheers,  
Wouter

**Comment by anja999** [comment]
Hi Wouter,

so I would like to have a file (table) with data where it will be written how many gigabases were produced in a specific time (as is shown in Comulativeyieldplot_gigabases figure) for each sample.

It is possible to get that king of data?

Best,

Anja

**Comment by wdecoster** [comment]
I assume you start from the sequencing_summary files? I'll reuse some code to write a script to do that, but I won't add it to NanoComp itself as I don't want to keep on adding new features.

**Comment by anja999** [comment]
Yes, I used sequencing_summary files (sorry for not mentioning before). If you could write and share the code will be super helpful. 
I think that I will then ask you about instruction how to use it if it is not in NanoComp program... do I need just to write/copy it in ssh and run it?

Many thanks and best regards,

Anja

**Comment by wdecoster** [comment]
On which operating system are you working?

**Comment by anja999** [comment]
Linux Mint

**Comment by wdecoster** [comment]
I'll have some code for you Monday morning (European time)

**Comment by anja999** [comment]
Great, looking forward to testing it.

Many thanks and best regards,

Anja

**Comment by wdecoster** [comment]
I've added `get_cumulative_yield_table.py` to the scripts folder of this repository. If you save the code to a file (or clone the repository) you can do the following:

`python get_cumulative_yield_table.py summary1.txt summary2.txt summary3.txt > my_table_of_cumulative_yields.tsv`

It takes any number of (compressed) summary files and writes a tab separated table to stdout.

If NanoComp is installed then also all dependencies for this script should be available.

**Comment by anja999** [comment]
Many thank for the script. I try it and it looks that is working, giving me all the data I need :).
I just don't know why it stops at 23:50 minutes since I was running for 48h.  Do you have any idea? It is about original data or the script? 
Again many thank!
Best,

Anja

**Comment by wdecoster** [comment]
Can you show me some of the output? I tested the script here on some PromethION summary files, but not exhaustively.

**Comment by anja999** [comment]
Oh, I am sorry, I didn't see write, so the first day is day 0 and the second day is say 1; and the time starts again.

So everything is OK. 

Many thanks for everything,

Anja

**Comment by wdecoster** [comment]
Happy to help!

**Comment by APZPM** [comment]
Hi again!
I was running the script just informatively but then I started wondering if there is any chance to have reads name as well in the tsv file? For now, I have the time and the gigabases produced.

Many thanks if you could help me again!

Anja
