### ISSUE TITLE
Normalized log transformed read length histogram seems wrong

### ISSUE THREAD

**Issue by mldmort** [wdecoster/nanocomp#20]
Hi Wouter,

I am running ngmlr and minimap2 on the same fastq files to compare their alignment performances. But looking at the normalized read length histograms it seems to me that the area under the plots are not the same. It makes the comparison more difficult. I guess the reason is due to different width of the bins in the two plots. Do you divide by the width to make sure that the area under the curves are consistent?

Thanks,
<img width="1262" alt="Screen Shot 2019-09-19 at 6 08 53 PM" src="https://user-images.githubusercontent.com/30185806/65291670-4c220f80-db09-11e9-90af-7e9636921d4e.png">

<img width="1262" alt="Screen Shot 2019-09-19 at 6 08 29 PM" src="https://user-images.githubusercontent.com/30185806/65291698-62c86680-db09-11e9-8536-fdf7a6842a40.png">

**Comment by wdecoster** [comment]
Hi,

The normalization of the histograms is not something that I do the math for, the plotly module does that (ref https://plot.ly/python/histograms/#normalized-histogram). 
From the [documentation](https://plot.ly/python/reference/#histogram-histnorm), using `histnorm=" probability"` leads to `the sum of all bin HEIGHTS equals 1`.

So you are right if you say that the area is not equal in these graphs.

**Comment by mldmort** [comment]
Thanks!

First off, I think you meant to run `python setup.py install` in the cloned directory.
So I ran the updated version and the results are as below:
The normalized histogram looks much nicer and easier to compare when the area under the curves is 1.

<img width="1264" alt="Screen Shot 2019-09-24 at 1 09 04 PM" src="https://user-images.githubusercontent.com/30185806/65546658-ccab8c00-decc-11e9-9ef3-a598ed1935d1.png">

<img width="1264" alt="Screen Shot 2019-09-24 at 1 09 17 PM" src="https://user-images.githubusercontent.com/30185806/65546674-d59c5d80-decc-11e9-95fd-bc3b67bfc32f.png">

**Comment by wdecoster** [comment]
What I meant was actually `pip install .` (with the `.`), but `python setup.py install` works too :)

I agree that in your example it looks much better. I'll make the new version available on PyPI.

Thanks for your feedback!

Wouter
