### ISSUE TITLE
Pysam UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 499: ordinal not in range(128)

### ISSUE THREAD

**Issue by Markestine** [wdecoster/nanocomp#22]
Hi,

I try to compare the result of differents Nanopore run.
I mapped all the fastq with minimap2. I sort my bam with samtools.

And when I try to launch Nanocomp --bam $bam1 $bam2 $bam3
I have this error message
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.6/concurrent/futures/process.py", line 175, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/usr/lib/python3.6/concurrent/futures/process.py", line 153, in _process_chunk
    return [fn(*args) for args in chunk]
  File "/usr/lib/python3.6/concurrent/futures/process.py", line 153, in <listcomp>
    return [fn(*args) for args in chunk]
  File "/usr/local/lib/python3.6/dist-packages/nanoget/extraction_functions.py", line 156, in process_bam
    samfile = check_bam(bam)
  File "/usr/local/lib/python3.6/dist-packages/nanoget/extraction_functions.py", line 108, in check_bam
    if not samfile.header['HD']['SO'] == 'coordinate':
  File "pysam/libcalignmentfile.pyx", line 542, in pysam.libcalignmentfile.AlignmentHeader.__getitem__
  File "pysam/libcalignmentfile.pyx", line 419, in pysam.libcalignmentfile.AlignmentHeader.to_dict
  File "pysam/libcalignmentfile.pyx", line 532, in pysam.libcalignmentfile.AlignmentHeader.__str__
  File "pysam/libcutils.pyx", line 94, in pysam.libcutils.from_string_and_size
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 499: ordinal not in range(128)
"""

And I dont know with I have this ascii issue. Any suggestions?

THanks in advance,
Marie-Christine

**Comment by wdecoster** [comment]
> I try to compare the result of differents Nanopore run.
> I mapped all the fastq with minimap2. I sort my bam with samtools.

Could you please add the exact commands you used before running NanoComp, and the command of NanoComp? Does on one of your filenames contain weird characters with accents or something like that?

**Comment by Markestine** [comment]
Hi,
thanks for your quickly answer.

For the mapping, I use this command
minimap2 -ax map-ont $fastq -t 2 > $output.sam

And for NanoComp
NanoComp --fastq $fastq1 $fastq2 $fastq3 --names names1 names2 names3 

And the output of the command line "echo $LANG"
fr_FR.UTF-8

**Comment by wdecoster** [comment]
No, that's not the command you used, as you previously mentioned you had problems with `NanoComp --bam`, and the error is clearly not related to fastq files. And are you using a SAM or a BAM file?

Do you think it would be possible to share your bam file for troubleshooting?

**Comment by Markestine** [comment]
Sorry I made a mistake I used --bam instead --fastq
NanoComp --bam $bam1.sort $bam2.sort -names bam1 bam2

And before run NanoComp, I sort the bam file with
samtools sort $bam > $bam.sort

**Comment by wdecoster** [comment]
Please try to answer all questions, if not I can't really troubleshoot. Also, just writing $bam2.sort is not really telling me a lot about the files you are working on.

> And are you using a SAM or a BAM file?

> Do you think it would be possible to share your bam file for troubleshooting?

> Does on one of your filenames contain weird characters with accents or something like that?

**Comment by Markestine** [comment]
Here the the real command line
NanoComp --bam all_nb2ft10_guppy_highaccurancy-vs-IRGSP1.0.sort.bam all_nb2ft10_flappie-vs-IRGSP1.0.sort.bam --names Guppy_HA Flappie

The files are sort BAM files.

And normally iinside these files there are not weird character, it's output of Minimapé converted in bam file.
I send you by mail a link with the bam files.

**Comment by wdecoster** [comment]
I downloaded your bam files, and unfortunately, it seems I cannot replicate your problem. It just runs without issue and must, therefore, be a local issue that I can't really troubleshoot.

You could try changing the language on your system: `export LANG=en_US.UTF-8`

**Comment by wdecoster** [comment]
Please let me know if there is anything I can help you with.
