### ISSUE TITLE
ValueError: max_workers must be greater than 0

### ISSUE THREAD

**Issue by Nazeeefa** [wdecoster/nanocomp#23]
Hi,

Just gave NanoComp a try running the following command:
`NanoComp --bam file1.bam file2.bam --title "nanopore comparison" --outdir .`

and received this exception:
```
File "/sw/bioinfo/NanoComp/1.9.2/bianca/lib/python3.6/site-packages/nanoget/extraction_functions.py", line 162, in process_bam
    with cfutures.ProcessPoolExecutor(max_workers=kwargs["threads"]) as executor:
  File "/sw/comp/python/3.6.8_rackham/lib/python3.6/concurrent/futures/process.py", line 394, in __init__
    raise ValueError("max_workers must be greater than 0")
ValueError: max_workers must be greater than 0
```
Any idea on how to resolve this? Thank you, I appreciate your help and time!

**Comment by wdecoster** [comment]
Thanks for reporting this. Did you install NanoComp with pip or conda?
Could you let me know the version of the nanoget submodule you have?

`python -c "import nanoget ; print(nanoget.__version__)"`

If it's older than v1.12.0, please try upgrading nanoget with:
`pip install nanoget -U`

**Comment by Nazeeefa** [comment]
Hi, I am unable to find the version of the nanoget submodule because apparently the module pandas is not installed.

**Comment by wdecoster** [comment]
That's odd. So definitely something is wrong in your installation. 

> Did you install NanoComp with pip or conda?

**Comment by wdecoster** [comment]
Let me know if you need further help!

**Comment by Nazeeefa** [comment]
Thank you, I'll let you know.
I am waiting for a reply from people who installed it on (secure) server.

Cheers,
Nazeefa
