### ISSUE TITLE
Calculating N50?

### ISSUE THREAD

**Issue by Maillinia** [wdecoster/nanocomp#26]
I was wondering why I do not get the same N50 value using nanocomp as when I calculate it myself.
I do the following
1.	Extract read lengths
2.	Order them with decreasing values
3.	Sum their values cumulative down through the list (cum_sum)
4.	Find the value that is above half of the maximum cumulative sum, and its corresponding read length [x > max(cum_sum)/2 ]

Does nanocomp do some kind of filtering before calculating the N50?

**Comment by wdecoster** [comment]
Hi,

There shouldn't be any filtering. Are you using reads in FASTQ, summary or BAM format? 
Did you calculate this in Python? This is the function of NanoComp to calculate the N50:

```
def get_N50(readlengths):
    """Calculate read length N50.
    Based on https://github.com/PapenfussLab/Mungo/blob/master/bin/fasta_stats.py
    """
    return readlengths[np.where(np.cumsum(readlengths) >= 0.5 * np.sum(readlengths))[0][0]]
```

Cheers,
Wouter

**Comment by wdecoster** [comment]
Did this function clarify anything or do you still see a difference?

**Comment by Maillinia** [comment]
I extract the read lengths using bioawk and then calculate the N50 in R.

**Comment by wdecoster** [comment]
So you are using fastq files? Does your code in R look similar to my function? Can you share your code?
