### ISSUE TITLE
Add option to get stats with --pickle analogous to NanoPlot

### ISSUE THREAD

**Issue by Sophie-Gallina** [wdecoster/nanocomp#27]

**Comment by wdecoster** [comment]
Would you mind adding just a little bit of a description here?

**Comment by Sophie-Gallina** [comment]
NanoComp can store pre-computed data to files using either --pickle or --store option
But, as far as I understand, NanoComp has no way to use these pre-computed data.
I would like to run NanoComp with 2 steps, 
1) compute statistics data and store them to a file (pickle or tsv.gz) : already OK
2) read data from this .pickle or .tsv.gz file to generate plots and reports more rapidly : todo
So that the first step, which is time consuming, will be run only once per fastq file, and then second step can be run quickly and many times to compare various sets of fastq files.
Thanks a lot.
Sophie

**Comment by wdecoster** [comment]
Hi Sophie,

Thanks for explaining. It's probably also the most polite thing to do?

Alright, adding pickle as input format sounds possible. I'll have a look at it later this week, maybe tonight. Note that things are already a lot faster if you use the sequencing_summary files generated by Guppy.

Cheers,
Wouter

**Comment by Sophie-Gallina** [comment]
Sorry for asking without any explanation, and thank you for your response.
sophie

**Comment by wdecoster** [comment]
This function should be available in NanoComp v1.11.1, but I have not tested it thoroughly and I don't have the time to do so. For that reason I have not added it to the documentation yet.
You can use it with `NanoComp --pickle file1.pickle file2.pickle file3.pickle --names name1 name2 name3` Please let me know if you see something unexpected.
