### ISSUE TITLE
reads above quality cutoffs	

### ISSUE THREAD

**Issue by LeilyR** [wdecoster/nanocomp#28]
Hi,
May I ask, how I should interpret the numbers under the  "Number, percentage and megabases of reads above quality cutoffs" section. Thanks a lot!

**Comment by wdecoster** [comment]
Reads are filtered for certain quality cutoffs, and the table lists the number of reads above that cut-off, the percentage of reads that are above that cut-off and the total contribution in megabases of those reads. Does that help?

**Comment by LeilyR** [comment]
thanks, so does it mean that if they are falling in >Q5 their quality is higher that 5?

**Comment by wdecoster** [comment]
Yes, the category >Q5 is for reads with an average basecall Phred quality score above 5, obtained by converting all Phred scores of a read (of each base) to probabilities, taking the average of these probabilities and converting that back to the Phred scale.
