### ISSUE TITLE
Running NanoComp with a pickle file

### ISSUE THREAD

**Issue by AMTZ-ssi** [wdecoster/nanocomp#30]
Hi.. I am trying to run NanoComp using pickle files generated by NanoPlot, however I keep experiencing the same problem. 

I run it like this: 
NanoComp --pickle BAAN1-NanoPlot-data.pickle BAAN2-NanoPlot-data.pickle BAAN3-NanoPlot-data.pickle --names BAAN1 BAAN2 BAAN3

And I get the following error:
Traceback (most recent call last):
  File "/srv/data/tools/public_envs/amtz_test_ont/bin/NanoComp", line 8, in <module>
    sys.exit(main())
  File "/srv/data/tools/public_envs/amtz_test_ont/lib/python3.8/site-packages/nanocomp/NanoComp.py", line 18, in main
    settings, args = utils.get_args()
  File "/srv/data/tools/public_envs/amtz_test_ont/lib/python3.8/site-packages/nanocomp/utils.py", line 246, in get_args
    if not len(args.names) == [len(i) for i in
IndexError: list index out of range

**Comment by wdecoster** [comment]
Hi,

Thanks for reporting this. I have an idea what goes wrong and I'll fix it as soon as possible.

Regards,
Wouter

**Comment by wdecoster** [comment]
Hi,

I believe I have fixed the problem, and the new code is available in NanoComp v1.11.3. Please let me know if you see anything unexpected.

Note: using .pickle files in NanoPlot and NanoComp is eventually going to get deprecated in favor of another file format (.feather). For a while both will exist side by side before I turn off .pickle support.

Regards,
Wouter

**Comment by AMTZ-ssi** [comment]
Thank you for your help and for the update of the program. It is running now without problems :)
