### ISSUE TITLE
release tag?

### ISSUE THREAD

**Issue by smoe** [wdecoster/nanocomp#32]
Cheers,
Steffen

**Comment by wdecoster** [comment]
Aha, another one!
https://github.com/wdecoster/nanocomp/releases/tag/1.12.0

I should probably be more pro-active on this, but after pushing new changes this escapes my attention... it should become a habit.

**Comment by smoe** [comment]
As responsive as you are - no problem. The motivation is that scripts on the Debian/conda/Fedora use those tags to auto-inform about new commits that you as upstream consider release-worthy and hence package-update worthy. And the versions look nicer than some git hash.
