### ISSUE TITLE
NanoComp fails with ValueError

### ISSUE THREAD

**Issue by utrivedi** [wdecoster/nanocomp#34]
Hello,
While trying to run the latest version of NanoComp on a pair of fastq files it fails which following error:
`"ValueError: Transform failed with error code 1: Failed to serialize document: Uncaught" `
My Command is:
`NanoComp --fastq SRR7447108_Av_JG3.fastq.gz SRR7449790_Av_CIP.fastq.gz --names Av_JG3 Av_CIP
`
Please could you help to resolve this? 
Many thanks,
Urmi

**Comment by wdecoster** [comment]
Thanks for reporting this, this is similar to https://github.com/wdecoster/NanoPlot/issues/207

Is it possible that you don't have an internet connection where you are running NanoComp?

This is something I hope to fix soon, in the meantime you can downgrade this by installing NanoPlot==1.32.1. My apologies for the inconvenience.

**Comment by wdecoster** [comment]
I will make time to fix it tomorrow.

**Comment by wdecoster** [comment]
This issue should be resolved in NanoPlot v1.33.1, which is now available on PyPI. Please let me know if you encounter further errors.

Regards,
Wouter
