### ISSUE TITLE
DeprecationWarning for nanomath

### ISSUE THREAD

**Issue by PanZiwei** [wdecoster/nanocomp#35]
Hi,
I am trying to use `NanoComp --summary file.txt` and got the following error:
```
$ NanoComp --summary *.txt
lib/python3.6/site-packages/nanomath/nanomath.py:132: DeprecationWarning:
Call to deprecated function errs_tab.
```
It can still generate relevant report though. Do you have any idea on the error?

Thanks for your help!

**Comment by wdecoster** [comment]
That's just a warning, nothing to worry about. Bit of sloppy programming on my end, but everything should work exactly as it used to without the warning.
