### ISSUE TITLE
feature request?

### ISSUE THREAD

**Issue by devonorourke** [wdecoster/nanocomp#4]
Hey Wouter,

Awesome set of tools you've made. Many thanks!

I work with a vertebrate genome and need to run multiple flow cells using the same input tissue/DNA source. Imagine I've completed a trio of flow cells: library01, library02, and library03. When I go to run Albacore, I generally point the base caller to act on a parent directory to all three libraries and generate a single set of outputs (as it's all the same DNA ultimately destined for a single assembly). I'm realizing with your tools it would have been simpler to just run Albacore on each library independently; something like:
```
NanoComp --summary lib01_summary.txt lib02_summary.txt lib03_summary.txt
```
What I'm wondering is if there's a way to pass a single summary file, but parse it by knowing something about the unique association of each library name within the `filename` field of the sequencing_summary.txt file. It seems like a part of the string within the first field uses whatever you named your sequencing run, thus it may be simple enough to find each match within the sequencing file of your three library names and use those to generate your comparisons.

In my case, it would be wonderful to be able to enter something like this:

```
NanoComp --summary sequencing_summary_ALL.txt --parseRun lib01 lib02 lib03
```

Hopefully that request makes sense. Thanks for your work in any event!

Devon

**Comment by wdecoster** [comment]
Hi Devon,

That's an interesting idea and I would like to implement it as well. I'll probably have a look at it on Monday, it should be feasible to have it all done by the end of the week, probably earlier.
Could you perhaps share a (partial) example of such a summary file? Then I can make sure I do this right.

Thanks for the suggestion! 
Wouter

**Comment by devonorourke** [comment]
Hi Wouter,  

Here's the first few lines of the `sequencing_summary.txt` file:
```
filename	read_id	run_id	channel	start_time	duration	num_events	passes_filtering	template_start	num_events_template	template_duration	num_called_template	sequence_length_template	mean_qscore_template	strand_score_template
macmanes_lab_local_20171027__MN23323_mux_scan_edgarB2_1d2_72018_read_399_ch_412_strand.fast5	1b3ba5a1-63d7-4029-9af3-41dc2292981b	a7a9e978fc27e642105108b95bcb2647af5f4c6c	412	392.23689	2.40156	1895	True	0.05544	1895	2.34612	1895	1055	11.944	-0.7732
macmanes_lab_local_20171027__MN23323_mux_scan_edgarB2_1d2_72018_read_213_ch_396_strand.fast5	29f7b8f7-4d9b-4a1f-b469-cb014b63108f	a7a9e978fc27e642105108b95bcb2647af5f4c6c	396	246.26394	11.86985	9402	True	0.17978	9402	11.69007	9402	5568	14.276	-0.5668
macmanes_lab_local_20171027__MN23323_mux_scan_edgarB2_1d2_72018_read_99_ch_38_strand.fast5	3e79e562-3b8e-48e8-a9b7-ce3c89af084e	a7a9e978fc27e642105108b95bcb2647af5f4c6c	38	418.04764	3.77673	2923	True	0.13894	2923	3.63778	2923	1649	12.057	-0.7586
```

It strikes me that the only consistent item in that list sits within the first field - the `filename` portion of that .txt file:
```
macmanes_lab_local_20171027__MN23323_mux_scan_edgarB2_1d2_72018_read_399_ch_412_strand.fast5
macmanes_lab_local_20171027__MN23323_mux_scan_edgarB2_1d2_72018_read_213_ch_396_strand.fast5
macmanes_lab_local_20171027__MN23323_mux_scan_edgarB2_1d2_72018_read_99_ch_38_strand.fast5
```

Specifically, the thing all these reads have in common is they were generated from a single MinKnow run: `macmanes_lab_local_20171027__MN23323_mux_scan_edgarB2_1d2`.  

So that still seems like quite a bit of a mess to type, right? What's interesting is that the thing I actually typed into MinKnow when first running this library was just `edgarB2_1d2`. My understanding then is that everything that preceeded `edgarB2_1d2` must be the path to the directory in which that file was created.   

In addition, provided you run the QC check in MinKnow prior to doing your sequencing run, every library run will create two files: (1) the QC file **{mux_scan_LibraryName}**; as well as the actual run (2) **{sequencing_run_LibraryName}**.  In fact, if we look into more of that `sequencing_summary.txt` file, you'd find that the contents include the following two `filename` strings, reflecting those two run types (I've posted just the first field this time instead of all 13 and broken up between directories with `---`):
```
macmanes_lab_local_20171027__MN23323_mux_scan_edgarB2_1d2_72018_read_399_ch_412_strand.fast5
macmanes_lab_local_20171027__MN23323_mux_scan_edgarB2_1d2_72018_read_213_ch_396_strand.fast5
macmanes_lab_local_20171027__MN23323_mux_scan_edgarB2_1d2_72018_read_99_ch_38_strand.fast5
---
macmanes_lab_local_20171027__MN23323_sequencing_run_edgarB2_1d2_90602_read_940_ch_416_strand.fast5
macmanes_lab_local_20171027__MN23323_sequencing_run_edgarB2_1d2_90602_read_2560_ch_96_strand.fast5
macmanes_lab_local_20171027__MN23323_sequencing_run_edgarB2_1d2_90602_read_3885_ch_404_strand.fast5
```

So in my world, I've not only run 1 QC run, plus 1 Library run, but _several_ QC and Library runs. Each MinKnow output contains a unique directory pertaining to each QC or Library, but ultimately I've run Albacore on all libraries at once. so my sequencing summmary contains a lot of unique strings. To keep things somewhat simple: 
- Imagine I've created two libraries: `edgarB1_1d2` and `edgarB2_1d2`
- To make it more complicated, imagine I restarted my `edgarB1` run after 12 hours, so though there is data originally generated and that first run, I've created another run named `edgarB1restart1_1d2`.
- Finally, recall that imagine I have a pair of libraries for each name, because there is always a pair of directories with **mux_scan** and **sequencing_run** files for each run.  

If that seems sensible, what I'm really saying is that there are 6 parent directories which Albacore would have run recursively through to find all my .fast5 files and make base calls. Here's a snippet of those:  
```
macmanes_lab_local_20171101_FAH30229_MN23323_mux_scan_edgarB1_1d2_60691_read_100_ch_160_strand.fast5
macmanes_lab_local_20171101_FAH30229_MN23323_mux_scan_edgarB1_1d2_60691_read_100_ch_404_strand.fast5
macmanes_lab_local_20171101_FAH30229_MN23323_mux_scan_edgarB1_1d2_60691_read_100_ch_406_strand.fast5
---
macmanes_lab_local_20171101_FAH30229_MN23323_sequencing_run_edgarB1_1d2_48617_read_100_ch_187_strand.fast5
macmanes_lab_local_20171101_FAH30229_MN23323_sequencing_run_edgarB1_1d2_48617_read_100_ch_228_strand.fast5
macmanes_lab_local_20171101_FAH30229_MN23323_sequencing_run_edgarB1_1d2_48617_read_100_ch_23_strand.fast5
---
macmanes_20171103_FAH30229_MN23323_mux_scan_edgarB1restart_1d2_33047_read_101_ch_34_strand.fast5
macmanes_20171103_FAH30229_MN23323_mux_scan_edgarB1restart_1d2_33047_read_101_ch_387_strand.fast5
macmanes_20171103_FAH30229_MN23323_mux_scan_edgarB1restart_1d2_33047_read_101_ch_398_strand.fast5
---
macmanes_20171103_FAH30229_MN23323_sequencing_run_edgarB1restart_1d2_89444_read_100_ch_173_strand.fast5
macmanes_20171103_FAH30229_MN23323_sequencing_run_edgarB1restart_1d2_89444_read_100_ch_228_strand.fast5
macmanes_20171103_FAH30229_MN23323_sequencing_run_edgarB1restart_1d2_89444_read_100_ch_270_strand.fast5
---
macmanes_lab_local_20171027__MN23323_mux_scan_edgarB2_1d2_72018_read_399_ch_412_strand.fast5
macmanes_lab_local_20171027__MN23323_mux_scan_edgarB2_1d2_72018_read_213_ch_396_strand.fast5
macmanes_lab_local_20171027__MN23323_mux_scan_edgarB2_1d2_72018_read_99_ch_38_strand.fast5
---
macmanes_lab_local_20171027__MN23323_sequencing_run_edgarB2_1d2_90602_read_940_ch_416_strand.fast5
macmanes_lab_local_20171027__MN23323_sequencing_run_edgarB2_1d2_90602_read_2560_ch_96_strand.fast5
macmanes_lab_local_20171027__MN23323_sequencing_run_edgarB2_1d2_90602_read_3885_ch_404_strand.fast5
```

As I mentioned in my request, what would be great is to find a way to parse through that sequencing_summary.txt file to compare the reads by the `filename` structure. In my example above, I'd like keep the pair of **mux_scan** and **sequencing_run** reads together, but just differentiate/compare my runs by the three libraries I've created (`edgarB1_1d2`, `edgarB1restart_1d2`, and `edgarB2_1d2`). To be more specific than my generic example in the first post:  

```
NanoComp --summary sequencing_summary_ALL.txt --parseRun edgarB1_1d2 edgarB1restart_1d2 edgarB2_1d2
```

What would be more powerful is to find a way to incorporate regular expressions into the `--parseRun` (or whatever make sense to call it) function. I'd imagine people would not only want to compare every individual run, but also just combine the sets of runs in which a restart was executed. For example, maybe I'd rather just compare both my `edgarB1` runs against the single `edgarB2`:

```
NanoComp --summary sequencing_summary_ALL.txt --parseRun edgarB1*_1d2 edgarB2_1d2
```

Thanks again for your help and the great set of tools!

**Comment by wdecoster** [comment]
Thanks for the elaborate reply and examples. This looks pretty complicated, I will think about it when I get to see a computer, tomorrow or Monday. Need to figure out a way to do this for all applications, without adding a thousand options.

**Comment by wdecoster** [comment]
Hi Devon,

I've made a first step in implementing this.
NanoComp v0.8.0 has now a `--split_runs` argument, which will use the run ids from the summary file to create separate datasets. The names will just lazily be "run1", "run2", etc.

I know that's not perfect, and not completely what you are looking for. A workaround for you would currently be to split the summary file up front, e.g. using grep:

```bash
cat \
 <(head -n1  sequencing_summary_ALL.txt) \
 <(grep edgarB1*_1d2 sequencing_summary_ALL.txt) \
 > summary1.txt
cat \
 <(head -n1  sequencing_summary_ALL.txt) \
 <(grep edgarB2_1d2 sequencing_summary_ALL.txt) \
 > summary2.txt
```
(the head -n1 parts are to keep the header...)

I'm just a bit reluctant to add this filename parsing mainly because it's pretty complicated to cover all use cases (users have infinite possibilities to screw up then) and because I was ignoring the filenames when getting the data from the summary. That last reason is not too hard to change.

I'll leave this open to think about this longer.

Please let me know if you have more feature requests!

Cheers,
Wouter

**Comment by devonorourke** [comment]
Cool. I hear you on the infinite possibilities problem. I might be asking the exact same thing as before with the file names, but your point about run number made me realize I should have been asking about using value in the filename string in the first place:

Using the same example as above, what I want to do is compare Library 1 to Library 2. In the table below, you can see from that list of file names as well as run Numbers that I want to group together for each Library:

| Library | run Name | run Number | 
| --- | --- | --- |
| Library 1 | mux_scan_edgarB1_1d2 | 60691 |
| Library 1 | sequencing_run_edgarB1_1d2 | 48617 |
| Library 1 | mux_scan_edgarB1restart_1d2 | 33047 |
| Library 1 | sequencing_run_edgarB1restart_1d2 | 89444 |
| Library 2 |mux_scan_edgarB2_1d2 |  72018 |
| Library 2 | sequencing_run_edgarB2_1d2 | 90602 |

I'm excited to use `--split_runs` and the grep search certainly won't be a problem, so thanks very much for implementing that option. 

I wonder if there would be an option that could use the run Numbers, not run Names, but would function in similar spirit to my earlier request. What if you asked the user to input a simple text file where they list two fields: the first field being the *Library* that `NanoComp` things as a single unit for comparison, and the *Run Number(s)* that you want to NanoComp to group together. Using the example as above, the `nanoList.txt` file to pass would look like:
```
Library 1,60691
Library 1,48617
Library 1,33047
Library 1,89444
Library 2,72018
Library 2,90602
```

The subsequent argument to pass then would invoke your `split_runs` argument by incorporating the text file above, like:
```
NanoComp --summary sequencing_summary_ALL.txt --split_runs nanoList.txt
```

I guess the only thing you'd want to watch out for is whether that txt file needed to be tab or comma or space delimited (at least there is probably a finite number of ways to screw up in this instance!)

Thanks as always,
Devon

**Comment by wdecoster** [comment]
Hi Devon,

I like your idea!

Correct me if I'm wrong, but isn't this "Run number" you mention above always the same for a certain "run id"? I haven't checked a lot of summary files, but in my test "234af351dcb969b3cb0e1b6b6a1af5762f62050b" in the third column ('run_id') always matches with "27220" as the integer in the filename, e.g. `nanopore2_20170303_FNFAF09967_MN17024_mux_scan_170301_MG1655_PC_RAD002_27220_ch509_read68_strand.fast5`

Parsing that file wouldn't be too hard - NanoComp could just throw an error if the format is not as expected and tell the user to fix the format. Parsing a regular expression in the filename part is hard - you never really know what is "not as expected".

Cheers,
Wouter

**Comment by devonorourke** [comment]
Yep - you're exactly right from what I can tell. If you look back at my comment from 4 days ago (the one where posted a lot of example data from my file names) you'll see the run number / run ID is the same for all files associated with a given run name. In other words, whatever name you enter into MinKnow, you also get a unique run number that follows. 

In your most recent example, the run ID of `27220` would be applied to every fast5 file that was part of the mux scan which someone must have entered into MinKnow as "_170301_MG1655_PC_RAD002 _".

Thanks and let me know what other information you might need.

**Comment by wdecoster** [comment]
Alright - I think I got what you are looking for in NanoComp v0.9.0.

NanoComp --split_runs takes a tab separated file now, which is expected to look like [this](https://github.com/wdecoster/nanocomp/blob/master/extra/split_file.tsv).
Meaning: a header with NAME and RUN_ID (actually not case-sensitive).

You specify the name you want for each dataset, together with the run IDs. run IDs which get the same name will get combined.

So - still not using the file numbers - but using the third column of the summary file because I was already extracting that from the summary file anyway.

Looking forward to your feedback on this!

**Comment by devonorourke** [comment]
Great - sorry I completely missed the whole point of the run ID being the third field of the summary file... I got it now.

In the case in which I have multiple run IDs associating with a single NAME, would the data table be structured as follows (I'm making up weird `run IDs` just to be make discriminating them real easy)?:

```
NAME	RUN_ID
runC	1234abcd5678efgh910ijklmnopqrstuvwxyz
runA	1111abcd5678efgh000zyxwvutsrqponmlkji
runA	9999abcd5678efgh111atcgatcgatcgatcgat
runD	0000abcd5678efgh888aaaaaaaaaaaaaaabbb
runD	6666abcd5678efgh666gowoutergowoutergo
```

In other words, would this generate three comparisons (Run A, C, and D) in a single sequencing_summary.txt file in which there are those 5 unique Run IDs?

What would the command I need to enter be?

**Comment by wdecoster** [comment]
Yes, that would work.

For example, reads with run_id `1111abcd5678efgh000zyxwvutsrqponmlkji` and `9999abcd5678efgh111atcgatcgatcgatcgat` would get merged together to form dataset runA and get displayed as one set in the plot.

Say that you called your file: "my-favorite-run-names.tsv" then you would simply do:
`NanoComp --summary sequencing_summary.txt --split_runs my-favorite-run-names.tsv`

NanoComp will check if the file exists and is as expected. I'm not sure if I covered all possible errors though.

**Comment by devonorourke** [comment]
Great. I'll give it a shot tonight and see what happens.

Unrelated request (and am happy to start a new thread on Github here - just let me know). Is there a way to generate a summary .txt file used in the plotting itself?  I'm in no way knowledgeable in Python, but on line 150 of the [main script](https://github.com/wdecoster/nanocomp/blob/master/nanocomp/NanoComp.py) it looks like you've defined a data frame and then are using that object to then apply one of a series of plotting options. Is there a way that someone could pass an added flag that would output not only the image itself, but the underlying data frame too (for example `--outputDF`)? 

Something like:
```
NanoComp --summary sequencing_summary.txt --split_runs my-favorite-run-names.tsv --outputDF
```

**Comment by wdecoster** [comment]
That's right. Essentially: the [nanoget module ](https://github.com/wdecoster/nanoget) is used to extract all metrics from the files (summary, fastq or bam) and then that information is passed to plotting function in [nanoplotter](https://github.com/wdecoster/nanoplotter). The main script NanoComp just takes care of the input arguments, handling the file to the nanoget functions and then sending the data to the nanoplotter functions.

NanoPlot already has an option to create a binary 'pickle' file of the DataFrame (which is a [pandas](http://pandas.pydata.org/) object) using `NanoPlot --store`. After creating such a pickle file you can use it again as input to NanoPlot using `NanoPlot --pickle`. Adding the same to NanoComp wouldn't be too hard.

For which purpose would you like the extracted summary file exactly?

**Comment by devonorourke** [comment]
Just thinking about potentially modified plots using external packages (I use ggplot a lot). Something as simple as adding subtitles, maybe more complex like faceted plots. Not sure exactly...
Thanks for the info about the overall process - very helpful.

**Comment by wdecoster** [comment]
I see, so a flat text file would be the most useful I assume. If you are using the albacore sequencing_summary.txt files then you already have everything in a table, so I assume this request is more about feature extraction from fastq or bam files?

If you have specific suggestions about which plots you would like to make I'd be happy to have a look at implementing those too. Adding titles to NanoComp plots is actually on my to-do list, something that I'll probably fix this week.

**Comment by devonorourke** [comment]
Hi Wouter,
Thanks for the earlier explanation about how to really incorporate the suite of tools; I didn't realize the utility behind the _pickle_ file but will try my best to get it to work for a few images I have in mind. One thing I've been trying to incorporate is a third dimension to the already [wonderful plot](https://github.com/wdecoster/NanoPlot/blob/master/examples/scaled_Log_Downsampled_LengthvsQualityScatterPlot_kde.png) examining read lengths and quality scores you've generated. Specifically, I want to see how a density plot like that is changing as a run progresses; I want to add that third _time_ dimension to that plot.
One way I had conceived of was bringing all this data into R, then using a Shiny app to incorporate a scroll bar which would dynamically change your 2D plot - imagine plotting exactly what you already have, but incorporating a scroll bar like [this example](https://shiny.rstudio.com/gallery/google-charts.html). But if [this site](https://plot.ly/python/range-slider/) is correct, whatever you can do in R can be done in Python anyway... but the idea is the same.
I don't really like that idea though, because the point is to see how the image changes over time in one shot - you want to see the entire distribution of variance in the quality score and read length over all the run in one image. But it's not like you can just stack heatmaps behind each other...
I don't know what the picture should look like though... 
One way would be to take a violin plot structure and just substitute the _run_ variable with time, binned by whatever increments the user assigns, or perhaps even simpler, every hour or two.  
I think it would be useful to compare runs against one another - this could still be visualized in a traditional [split violin](http://seaborn.pydata.org/examples/grouped_violinplots.html) plot, keeping runs and quality scores or read lengths on their normal axes, but adding in the element of the run comparisons as you already have featured. 
Maybe yet another way one could approach this problem is to use what I think has been called a ["_ridges_"](https://github.com/clauswilke/ggridges) plot, which is essentially a split violin plot turned sideways. The x axis is still run time and y axis is either the quality score or read length as above, but I think it's easier to see how these things shift when their nested vertically rather than horizontally for some reason.[This also exists](https://seaborn.pydata.org/examples/kde_joyplot.html) in seaborn already. I think there's a lot that can be learned from those kinds of plots:
1. How are lengths/quality scores shifting over your run? Do those change if you spike in more library? Do those change if you restart your run?
2. How are values shifting over time between runs? Are they consistent?
3. How do values vary across runs of different prep types?

**Comment by wdecoster** [comment]
Hi Devon,

Converting a pickle file to a flat text file could be done in a few lines of python:

```python
import pickle
import sys

print(pickle.load(open(sys.argv[1], 'rb')).to_csv(sep="\t", index=False))
```
You could save this as "unpickle.py" and then do:

`python unpickle.py NanoPlot-data.pickle > myoutputfile.tsv`

But I'll add a `--raw` option to NanoPlot and NanoComp, probably today, which will create a tab separated file. The difference in disk space is not huge so it doesn't hurt to use text files rather than a compressed binary file. The pickle has the advantage that it's very easy to reuse (and import in NanoPlot) the same data again as a _pandas DataFrame_ for making new plots.


As you said, there are a ton of options for plotting. Indeed, everything that you can do in R you can do in Python as well ;-)
There are some other scripts for Nanopore data plotting, you could also check out [pycoQC](https://github.com/a-slide/pycoQC) and [minion_qc](https://github.com/roblanf/minion_qc). They may already have a few of the plots you are looking for.

I have it on my todo list to also look at "moving 3D plots" and "plots with slide bars" but that's something I still have to dive into. I'll make some first attempts this weekend but I'm not sure when I'll have a working project. The trouble with this kind of plots (I expect) is that you are looking thousands of data points and you still want the transitions to be smooth. 

I find the violin plots showing how length and quality evolve over time already quite informative. So you would suggest comparing quality over time of two runs using split violin plots? That can be done, but what if you want 3 runs? Perhaps ridges plots are more suitable, or using a "[grouped boxplot](http://seaborn.pydata.org/examples/grouped_boxplot.html)" or "grouped violin plot". 

It seems you have a lot of interesting ideas, so I don't know where to start. Do you also have a specific feature request?

Thanks for all the feedback and ideas!
