### ISSUE TITLE
TypeError: write_stats() got an unexpected keyword argument 'as_tsv'

### ISSUE THREAD

**Issue by Annie-msi** [wdecoster/nanocomp#40]
Hello,
I used this command to compare 5 nanopore runs and getting this following error:

NanoComp --summary CFrun1_sequencing_summary.txt CFrun2_sequencing_summary_FAO02660_9be575fb.txt WCrun1_sequencing_summary.txt WCrun3_sequencing_summary_FAO69991_ee9098dc.txt Winona_sequencing_summary_FAP07387_60b4a7a5.txt  --names A B C D E
Traceback (most recent call last):
  File "/home/plarsen/jahan036/miniconda3/envs/Nanocomp/bin/NanoComp", line 10, in <module>
    sys.exit(main())
  File "/home/plarsen/jahan036/miniconda3/envs/Nanocomp/lib/python3.6/site-packages/nanocomp/NanoComp.py", line 72, in main
    as_tsv=args.tsv_stats)
TypeError: write_stats() got an unexpected keyword argument 'as_tsv'

**Comment by wdecoster** [comment]
Hi,

Thanks for reporting this. Could you let me know how you installed NanoComp? It seems the nanomath submodule is outdated, which you could update using either `pip install nanomath ---upgrade` or `conda upgrade nanomath`.

Cheers,
Wouter

**Comment by Annie-msi** [comment]
I used conda install with the following command 
conda install -c bioconda NanoComp
And i did 'conda upgrade nanomath'
'(Nanocomp) jahan036@ln0003 [~] % conda upgrade nanomath
Solving environment: done

==> WARNING: A newer version of conda exists. <==
  current version: 4.5.4
  latest version: 4.9.2

Please update conda by running

    $ conda update -n base conda



# All requested packages already installed."
Then i ran the same command 
"NanoComp --summary CFrun1_sequencing_summary.txt CFrun2_sequencing_summary_FAO02660_9be575fb.txt WCrun1_sequencing_summary.txt WCrun3_sequencing_summary_FAO69991_ee9098dc.txt Winona_sequencing_summary_FAP07387_60b4a7a5.txt --names A B C D E"
Got following error
Traceback (most recent call last):
  File "/panfs/roc/groups/0/plarsen/jahan036/miniconda3/envs/Nanocomp/bin/NanoComp", line 10, in <module>
    sys.exit(main())
  File "/home/plarsen/jahan036/miniconda3/envs/Nanocomp/lib/python3.6/site-packages/nanocomp/NanoComp.py", line 72, in main
    as_tsv=args.tsv_stats)
TypeError: write_stats() got an unexpected keyword argument 'as_tsv'

I tried to update conda and following error occured
"(Nanocomp) jahan036@ln0003 [~/Nanocomp_results] % conda update -n base conda
Solving environment: failed

InvalidVersionSpecError: Invalid version spec: =2.7"

**Comment by Annie-msi** [comment]
I reinstalled using mamba, its working now.
Thanks
