### ISSUE TITLE
Seaborn requirement should be added to setup

### ISSUE THREAD

**Issue by seanrj-conagen** [wdecoster/nanocomp#43]
Installing nanocomp using pip on a fresh python3 environment lacks the seaborn prereq.

seaborn should be added to setup.py.

Right about here, I think:
https://github.com/wdecoster/nanocomp/blob/fd900d05bb2fb8a7189a0c733647f2aa0c9e9ee6/setup.py#L40

**Comment by wdecoster** [comment]
Hi,

Thanks for reporting this. But in fact, seaborn is not used anymore. I noticed we forgot to remove an import statement, probably leading to the error you saw. We will fix it soon!

Cheers,
Wouter

**Comment by seanrj-conagen** [comment]
Thanks. Yes, it was having an error on the import statement at the top of utils.py.

**Comment by wdecoster** [comment]
This should be solved in NanoComp v1.14.1, please let us know if you notice further issues!
