### ISSUE TITLE
NanoComp: error: unrecognized arguments: --names

### ISSUE THREAD

**Issue by arz19893** [wdecoster/nanocomp#46]
Hi 
I am trying to use nanocomp for comparison pre post filter 
, I keep getting this error ): 

NanoComp --fastq 1149_AV_CIP.fastq.gz 1149_AV_CIP_trimmed.fastq.gz --names Av_CIP Av_CIP_trim -o Av_Nanocomp

**Comment by wdecoster** [comment]
Thanks for reporting this. Could you let me know how you installed NanoComp and which version you currently have?

**Comment by arz19893** [comment]
> Thanks for reporting this. Could you let me know how you installed NanoComp and which version you currently have?
Thank you for quick response 

The version is NanoComp 1.15.0
pip install NanoComp

**Comment by wdecoster** [comment]
Highly remarkable. It should work like that... also the testing code works with --names.
Are you copy-pasting this command from somewhere? Can you try just typing it to make sure there are no invisible characters?
