### ISSUE TITLE
TypeError: write_stats() got an unexpected keyword argument 'datadfs'

### ISSUE THREAD

**Issue by GabyBG** [wdecoster/nanocomp#5]
Hi I was trying to use NanoComp but when I run the command : NanoComp -t 12 --outdir /som/gbalderr/nanopore/ONT01vsONT02 --fastq /som/gbalderr/nanopore/run/ONT01_raw.fastq /som/gbalderr/nanopore/run/ONT02_raw.fastq --runs Run1 Run2

I got this:
Traceback (most recent call last):
  File "/data/users/gbalderr/anaconda3/bin/NanoComp", line 11, in <module>
    sys.exit(main())
  File "/data/users/gbalderr/anaconda3/lib/python3.6/site-packages/nanocomp/NanoComp.py", line 50, in main
    names=identifiers)
TypeError: write_stats() got an unexpected keyword argument 'datadfs'

am I doing something wrong?

Thank you for your help

**Comment by wdecoster** [comment]
Could you try updating a submodule?

`pip install nanomath - U`
