### ISSUE TITLE
Feature Request: Pore and cumulative yield comparisons?

### ISSUE THREAD

**Issue by schorlton** [wdecoster/nanocomp#50]
Thanks for your amazing tools! I'm wondering if it's possible to use NanoComp to produce overlaid versions of the NanoPlot `ActivePores_Over_Time.html` and `CumulativeYieldPlot_Gigabases.html` for multiple FASTQ files? Thanks again!

**Comment by wdecoster** [comment]
Those plots are created when you use the summary files as input, is that an option for you?

**Comment by schorlton** [comment]
Unfortunately I only have access to `fastq_rich` files and saw that NanoPlot creates these plots but combines the FASTQs so I was curious if possible to plot multiple sequencing runs on the same scatter plot from FASTQ 🙂

**Comment by wdecoster** [comment]
I do some fun-coding every night and this would fit, but it depends on if the baby feels like sleeping ;-)

**Comment by wdecoster** [comment]
`--fastq_rich` as input is added in NanoComp v1.18.0 :-)

**Comment by schorlton** [comment]
Awesome!! Thank you so much!

Minor thing I noticed (and may be separate issue): any idea what's going on with y axis label units? I don't believe I noticed this in NanoPlot:
![image](https://user-images.githubusercontent.com/10245822/153942031-b4a75dfb-16e6-47e6-b915-ce936b58ffa2.png)

**Comment by wdecoster** [comment]
Hmm bit weird indeed, is this by chance a really small dataset?

**Comment by schorlton** [comment]
It is indeed, I just took the first 100 lines of a FASTQ:
```shell
General summary:               barcode01.fastq       barcode02.fastq
Active channels:                         174.0                 173.0
Mean read length:                      2,149.1               2,149.1
Mean read quality:                        10.3                  10.3
Median read length:                    2,455.0               2,455.0
Median read quality:                      10.4                  10.4
Number of reads:                         250.0                 250.0
Read length N50:                       2,514.0               2,514.0
STDEV read length:                     1,553.4               1,553.4
Total bases:                         537,276.0             537,276.0
Number, percentage and megabases of reads above quality cutoffs
>Q5:    250 (100.0%) 0.5Mb      250 (100.0%) 0.5Mb
>Q7:    250 (100.0%) 0.5Mb      250 (100.0%) 0.5Mb
>Q10:   173 (69.2%) 0.4Mb       173 (69.2%) 0.4Mb
>Q12:   1 (0.4%) 0.0Mb  1 (0.4%) 0.0Mb
>Q15:   0 (0.0%) 0.0Mb  0 (0.0%) 0.0Mb
Top 5 highest mean basecall quality scores and their read lengths
1:      12.2 (493)      12.2 (493)
2:      11.7 (405)      11.7 (405)
3:      11.6 (452)      11.6 (452)
4:      11.5 (2591)     11.5 (2591)
5:      11.5 (1424)     11.5 (1424)
Top 5 longest reads and their mean basecall quality score
1:      24342 (10.9)    24342 (10.9)
2:      2645 (9.8)      2645 (9.8)
3:      2623 (10.9)     2623 (10.9)
4:      2621 (10.6)     2621 (10.6)
5:      2621 (10.7)     2621 (10.7)
```

**Comment by wdecoster** [comment]
Hmm yes the code is slightly different between NanoComp and NanoPlot. I will make a note of this, but I don't think changing this has a high priority, would you agree?

**Comment by schorlton** [comment]
You're the dev so I can only flag issues/request features/appreciate your hard work but I can't prioritize as I'm not the one making the actual changes (at this point) :stuck_out_tongue_closed_eyes: 

Closing this issue as you've very kindly added in the `--fastq_rich` feature. Won't open a new issue as you know about the units thing and will leave to you :smile:
