### ISSUE TITLE
Use .txt file of filepaths to multiple fastq files as input

### ISSUE THREAD

**Issue by ew367** [wdecoster/nanocomp#51]
Hi

I would like to compare multiple runs (~12) and was wondering if there was any way to use a text file (or similar) containing file paths for the individual fastq files as input (and for the --names arg) to nanoComp, rather than having to type them all out individually? 

Thanks

**Comment by wdecoster** [comment]
Hi,

At the moment that is not possible, but I agree that would make sense. I won't be able to make a promise when I would have the time to implement that though.

Wouter

**Comment by ew367** [comment]
No worries and thanks for getting back to me :)
