### ISSUE TITLE
How to modify axis limits/or reduce read length

### ISSUE THREAD

**Issue by hKilili** [wdecoster/nanocomp#52]
Hi,

Thank you very much for developing this very useful tool. I have an issue with violin plots and I was hoping that I could get help from here. When NanoComp plots violin plot for Read Lengths, y axis goes up to 18000 as I have few reads around that. However, my mean read length is around 700. So, I need to somehow either set the y axis limits or remove very high read lengths to get a nice violin plot and decide on my trimming strategy.  I normally use R, and tried to apply some codes I know from it but of course it didn't work. Could you please give me an advice what I can do?

Thank you very much.
Hus

<img width="604" alt="image" src="https://user-images.githubusercontent.com/79784594/161999972-f650212b-6dbb-4c63-ba46-f91a6fb7e285.png">

**Comment by wdecoster** [comment]
There is a --maxlength option to remove reads longer than a certain cutoff.
