### ISSUE TITLE
Autoscale outputs

### ISSUE THREAD

**Issue by schorlton** [wdecoster/nanocomp#55]
Thanks as always for the awesome tool(s). Quick question: is it possible to autoscale the units for the number on the right of this plot like the y-axis?
![image](https://user-images.githubusercontent.com/10245822/167755827-5b1ef10b-96ae-4b55-8891-4ff6426bfa63.png)

For the active pores over time, does it make sense to always include 0 as y-axis minimum? It's somewhat confusing when the plot starts like so:
![image](https://user-images.githubusercontent.com/10245822/167756112-3227cbfb-f562-4125-a3a0-c0c7788aaa74.png)

but zooming out reveals:
![image](https://user-images.githubusercontent.com/10245822/167756075-13c80e7d-adf5-4f52-a080-8470e271387c.png)
This one seems more minor but just a thought. Thanks again!!

**Comment by wdecoster** [comment]
Some good suggestions there, thanks. I will try to look into those, but I won't be able to promise when that is going to happen.

**Comment by wdecoster** [comment]
And it took a while, but these request have been somewhat addressed in NanoComp v1.19.3.
The number on the right in the yield plot is still in gigabases (like the y-axis), but has more decimals when rounding.
The active pores over time plots are adapted to include 0.

**Comment by schorlton** [comment]
Thank you :tada:
