### ISSUE TITLE
about extreme base call quality score

### ISSUE THREAD

**Issue by prasundutta87** [wdecoster/nanocomp#56]
Hi @wdecoster ,

I am using  NanoComp v1.17.0  and have compared fastq files. If you see the attached plots some sample have extreme outlier scores which has gone >80 or >40. Is this an error (because its only in a few cases). Do per base quality scores really go that high?

Command used:
`NanoComp --fastq <fastq.gz list> --name <name list> --dpi 300 --plot box --format png -t 16 --raw --readtype 1D --outdir QC/NanoComp_fastqs`
![average_base_call_quality_scores](https://user-images.githubusercontent.com/25484608/170712182-8ff2906f-58cf-433e-b2cc-be82abc7d4f4.png)

Regards,
Prasun

**Comment by wdecoster** [comment]
I think if you search for the exact read that caused this you will find a very short read, I've seen such artifacts before but not with recent versions of the basecaller.

**Comment by prasundutta87** [comment]
Thanks @wdecoster for your reply. I will check the guppy base caller used for my samples. Is there a quick way to extract the read with the high base quality score?
