### ISSUE TITLE
Bar labels swapped for 'total_throughput' graph

### ISSUE THREAD

**Issue by cdebuck** [wdecoster/nanocomp#58]
Hello,
I've used NanoComp v1.19 both with summary files and fastq files (each time with a pair of input files). I've used the -n parameter to give names to my samples.
I noticed that the graph called 'comparing throughput in bases' in the NanoComp report (= NanoComp_total_throughput.png) assigns the wrong labels to the bars, because it does not match the numbers from the NanoStats.txt file.
Also for the 'number of reads' graph, the labeling is correct, but the order of the bars is swapped compared to the other graphs, making it harder to interpret (because it first reports 'name-label-2' and then 'name-label-1'.

The command I've used is:
`NanoComp --summary sum_file_1 sum_file_2 -t 16 -n guppy_102 bonito_102 -o outdir`

![NanoComp_total_throughput](https://user-images.githubusercontent.com/61322543/179930751-f12d5b90-45bd-43eb-a58d-efd4436f013d.png)
![NanoComp_number_of_reads](https://user-images.githubusercontent.com/61322543/179930786-f0b3f3da-af78-44e2-b2a1-03689303be7c.png)
[NanoStats.txt](https://github.com/wdecoster/nanocomp/files/9147832/NanoStats.txt)

**Comment by wdecoster** [comment]
Hi,

Thanks for the report, that should be fixed in NanoComp v1.19.1, which I just pushed to PyPI and should available through conda within a few hours.

Wouter
