### ISSUE TITLE
Weighted Histograms? 

### ISSUE THREAD

**Issue by adramir4** [wdecoster/nanocomp#60]
I'm wondering if there would be an easy/clean way to get Nanocomp to produce (overlayed) weighted histograms similar to the ones produced by NanoPlot for comparison between samples? I don't know if I missed something in the code or if it was just not included for coding reasons beyond my understanding (very limited Python experience)

**Comment by wdecoster** [comment]
Hi,

Thanks for the suggestion, that is totally possible. I'll put it in my to-do list :-) 

Wouter

**Comment by wdecoster** [comment]
That took much longer than I anticipated, but here it is in v1.22 :)
Through pip you can already get it, bioconda will follow later today.
