### ISSUE TITLE
different total reads for fastq and bam file

### ISSUE THREAD

**Issue by prasundutta87** [wdecoster/nanocomp#62]
Hi @wdecoster ,

When I calculated the stats for a fastq file, I got a particular number of total reads. When I aligned those reads and calculated stats using nanocomp, I saw the total read number increased. What could be the reason for this? Could you please help me interpret this difference?

Regards,
Prasun

**Comment by wdecoster** [comment]
The difference is that from fastq the number of reads are used, while from a bam file the number of alignments is used. A single read can give one primary and multiple supplementary alignments, e.g. in the case of a structural variant.

**Comment by prasundutta87** [comment]
Hi @wdecoster..thanks a lot for this! I actually ended up comparing various stats from samtools flagstat, qualimap with nanocomp and understood that its due to supplementary alignments. Hence, I had closed the issue. Sorry for the trouble!
