### ISSUE TITLE
Barcodes in wrong order

### ISSUE THREAD

**Issue by cmfield** [wdecoster/nanocomp#65]
I'm using v 1.13.1 apparently, so apologies if this has already been fixed, but when I run the program with --barcoded to get say, a plot of quality distributions, or length distributions, the barcodes are in an arbitrary order (I suspect the order in which they are first encountered). It would be helpful if the default was to order them by number, 01, 02.. 24, unclassified.

**Comment by wdecoster** [comment]
I agree that would make sense. Will fix!

**Comment by wdecoster** [comment]
Should be fixed in v1.21.2 :-)

**Comment by cmfield** [comment]
> 

Brilliant!
