### ISSUE TITLE
 Length of values (5) does not match length of index (2)

### ISSUE THREAD

**Issue by Ulle22** [wdecoster/nanocomp#67]
Hi,

We have used your program before without any issues, but now when we are trying to run with multiple fasta files that only consist one or two contigs it is creating this issue: "Length of values (5) does not match length of index (2)". After some time we figured out that it something to do with the function get_top_5() in nanomath.py. If we put all contigs into one fasta file it will run, but then it is only one run.

The datadfs look like this:

[   lengths dataset  length_filter
0  1855841    run1           True
1    37744    run1           True,    lengths dataset  length_filter
2  16373730    run2           True
3   26651    run2           True,    lengths dataset  length_filter
4  1833377    run3           True,    lengths dataset  length_filter
5  1878807    run4           True,    lengths dataset  length_filter
6  1822655    run5           True,    lengths dataset  length_filter
7  17644453    run6           True,    lengths dataset  length_filter
8  1876627    run7           True]

Are we doing something wrong?

Ulle22

**Comment by wdecoster** [comment]
Hi,

This is not what nanocomp was designed for, and I am not sure what you aim to achieve. NanoComp expects individual reads from a sequencer, not assembled contigs. I think you should also have received a message like `WARNING: less than 5 reads in the dataset!`. 

Wouter

**Comment by wdecoster** [comment]
Your reads could be in fasta format, so same as fastq but without quality scores
