### ISSUE TITLE
Empty JSON files / want to format and edit font along plot axes

### ISSUE THREAD

**Issue by HornDW** [wdecoster/nanocomp#75]
Hi,

I was intending to edit/generate more readable plots by adjusting the font size / bolding the text along the axes. 

I tried adding the format option to create a JSON file for each of the generated plots with the hopes that I could use these files to create new, formatted graphs. I input arrow files using the --feather command as the original BAMs were quite large.

The usual graphs were generated as expected, however the JSON files were empty. 

I've attached the log 
[NanoComp_20240103_1410.log](https://github.com/wdecoster/nanocomp/files/13820464/NanoComp_20240103_1410.log)

**Comment by wdecoster** [comment]
I will try to look into this soon!

**Comment by HornDW** [comment]
Hi, 

Have you had a chance to look at this? Christos would like me to change the scale of the Y-axis on some graphs / make them more readable for a figure. I was hoping to find a way to edit the JSONs to do this.

**Comment by wdecoster** [comment]
Honestly, I think the easiest would be to clone the repository, and make the chances you want in the python code. Happy to help with that. Which plot(s) would you like to improve?

**Comment by HornDW** [comment]
Thanks, will give that a try.

I'm trying to improve the axes of the violin plots.

**Comment by wdecoster** [comment]
Now this took me a rather long time, but I was looking into this today, and at least for me the json files are not empty... Hope you found an other way to do what you want!
