### ISSUE TITLE
NanoComp_quals_violin question

### ISSUE THREAD

**Issue by MariBGO** [wdecoster/nanocomp#78]
Hi, thank you for a great tool! 

I have a question to the violin plot called NanoComp_quals_violin. The Y axis reads "Average base call quality score", so I was wondering if the plot represents **read** quality as calculated by average base quality described [here ](https://gigabaseorgigabyte.wordpress.com/2017/06/26/averaging-basecall-quality-scores-the-right-way/) or if it is a representation of all base qualities in the files, independent of reads?

kind regards,
Mari

**Comment by wdecoster** [comment]
Hi Mari,

Your first explanation was correct, it shows the distribution of the average quality score for each read.

Wouter
