### ISSUE TITLE
NanoStats.txt file output

### ISSUE THREAD

**Issue by devonorourke** [wdecoster/nanocomp#8]
Hi Wouter,
The last of the three data tables in the `NanoStats.txt` file output, where the header is "**Number and percentage of reads above quality cutoffs**"... When you look down the left hand column, there are values numbered 1 through 5. I think in an earlier version of the program these were things like Q > 5, Q > 10, etc. 
Thanks for clearing up how to interpret that dataset,
Devon

**Comment by wdecoster** [comment]
Good catch, that should still be these quality cutoffs. I'll have an update available in a couple of minutes.
Thanks again!

**Comment by wdecoster** [comment]
Updating the nanomath submodule will solve this!

    pip install -U nanomath
