### ISSUE TITLE
Name order not kept in final graphical outputs

### ISSUE THREAD

**Issue by damientully** [wdecoster/nanocomp#9]
Hi Wouter,

So when I run
`NanoComp --bam BC08_30.sorted.bam BC08_60.sorted.bam BC08_120.sorted.bam BC08_360.sorted.bam BC08_720.sorted.bam BC08_1440.sorted.bam BC08_final.sorted.bam -n 30mins 1hr 2hr 6hr 12hr 24hr 43hr`

it gives the following output and as you can see the input order is now completely re-arranged. This doesn't happen if you just label 1 2 3 4 5 ....etc
![nanocomp_number_of_reads](https://user-images.githubusercontent.com/17030873/35149075-c8f2aeae-fce2-11e7-903d-5f10da583cd9.png)

**Comment by wdecoster** [comment]
I've to agree that's not optimal. They are now sorted alphabetically but sorting by input would indeed be better. I'll have a look.

**Comment by wdecoster** [comment]
If you update the nanoplotter submodule to 0.32.0 then your datasets will be sorted as expected.

    pip install nanoplotter -U

I don't remember why I put in sorting in the first place. I probably had a good reason for that, but can't remember. Maybe for a barcoded run. Anyway. Thanks for your feedback!
